version: '3.8'

services:
  postgres-test:
    image: postgres:16-alpine
    container_name: kpost-postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kpost_test
    ports:
      - '5442:5432'
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 3s
      timeout: 3s
      retries: 10

  postgres-stats-test:
    image: postgres:16-alpine
    container_name: kpost-postgres-stats-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kpost_stats_test
    ports:
      - '5443:5432'
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 3s
      timeout: 3s
      retries: 10

  redis-test:
    image: redis:7-alpine
    container_name: kpost-redis-test
    ports:
      - '6389:6379'
    tmpfs:
      - /data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 3s
      timeout: 3s
      retries: 10
